java_binary(
    name = "race_condition_example",
    srcs = ["RaceConditionExample.java"],
    main_class = "concurrency.RaceConditionExample",
)

java_binary(
    name = "race_condition_atomic",
    srcs = ["RaceConditionAtomic.java"],
    main_class = "concurrency.RaceConditionAtomic",
)

java_binary(
    name = "race_condition_lock",
    srcs = ["RaceConditionLock.java"],
    main_class = "concurrency.RaceConditionLock",
)
